## Import libraries

In [57]:
import warnings
warnings.filterwarnings("ignore")

In [58]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report,confusion_matrix,accuracy_score,precision_recall_fscore_support
from sklearn.metrics import f1_score,roc_auc_score
from sklearn.ensemble import RandomForestClassifier,ExtraTreesClassifier
from sklearn.tree import DecisionTreeClassifier
import xgboost as xgb
from xgboost import plot_importance

## Anomaly-based IDS - Infiltration

### Generate the port-scan datasets for unknown attack detection

In [59]:
df=pd.read_csv('CICIDS2018_sample_km.csv')

In [60]:
df

Protocol  Flow Duration  Total Fwd Packets  Total Backward Packets  \
0     -0.475925      -0.005346          -0.020438               -0.040784   
1     -0.475925      -0.005361          -0.020438               -0.040784   
2     -0.475925      -0.005399          -0.020438               -0.040784   
3     -0.475925      -0.005334          -0.020438               -0.040784   
4     -0.475925      -0.005453          -0.020438               -0.040784   
...         ...            ...                ...                     ...   
36452  1.944820      -0.018959          -0.020859               -0.035722   
36453  1.944820      -0.018959          -0.020859               -0.035722   
36454  1.944820      -0.018959          -0.020859               -0.035722   
36455  1.944820      -0.018959          -0.020859               -0.035722   
36456  1.944820      -0.018959          -0.020859               -0.035722   

       Fwd Packets Length Total  Bwd Packets Length Total  \
0                     -0.020339                 -0.022177   
1                     -0.020339                 -0.022177   
2                     -0.020339                 -0.022177   
3                     -0.020339                 -0.022177   
4                     -0.020339                 -0.022177   
...                         ...                       ...   
36452                 -0.019875                 -0.021916   
36453                 -0.019875                 -0.021916   
36454                 -0.019875                 -0.021916   
36455                 -0.019885                 -0.021920   
36456                 -0.019875                 -0.021916   

       Fwd Packet Length Max  Fwd Packet Length Min  Fwd Packet Length Mean  \
0                  -0.830722              -0.361301               -0.961988   
1                  -0.830722              -0.361301               -0.961988   
2                  -0.830722              -0.361301               -0.961988   
3                  -0.830722              -0.361301               -0.961988   
4                  -0.830722              -0.361301               -0.961988   
...                      ...                    ...                     ...   
36452              -0.704356               1.437948               -0.330935   
36453              -0.704356               1.437948               -0.330935   
36454              -0.704356               1.437948               -0.330935   
36455              -0.707164               1.397965               -0.344959   
36456              -0.704356               1.437948               -0.330935   

       Fwd Packet Length Std  ...  Fwd Seg Size Min  Active Mean  Active Std  \
0                  -0.776052  ...          0.187746    -0.070847   -0.057248   
1                  -0.776052  ...          0.187746    -0.070847   -0.057248   
2                  -0.776052  ...          0.187746    -0.070847   -0.057248   
3                  -0.776052  ...          0.187746    -0.070847   -0.057248   
4                  -0.776052  ...          0.187746    -0.070847   -0.057248   
...                      ...  ...               ...          ...         ...   
36452              -0.776052  ...         -1.492618    -0.070847   -0.057248   
36453              -0.776052  ...         -1.492618    -0.070847   -0.057248   
36454              -0.776052  ...         -1.492618    -0.070847   -0.057248   
36455              -0.776052  ...         -1.492618    -0.070847   -0.057248   
36456              -0.776052  ...         -1.492618    -0.070847   -0.057248   

       Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label  
0       -0.085188   -0.058141   0.007993 -0.001875  0.002505  0.039759      6  
1       -0.085188   -0.058141   0.007993 -0.001875  0.002505  0.039759      6  
2       -0.085188   -0.058141   0.007750 -0.001875  0.002402  0.038739      6  
3       -0.085188   -0.058141   0.007993 -0.001875  0.002505  0.039759      6  
4       -0.085188   -0.058141   0.00775

In [61]:
df.Label.value_counts()

Label
0     10663
10     9908
6      5748
4      1989
5      1730
8      1448
1      1440
12     1183
14      943
2       568
7       415
3       229
13       85
9        55
11       53
Name: count, dtype: int64

In [62]:
df1 = df[df['Label'] != 4]
df1['Label'][df1['Label'] > 0] = 1
df1.to_csv('./CICIDS2017_sample_km_without_infiltration.csv',index=0)

In [63]:
df2 = df[df['Label'] == 4]
df2['Label'][df2['Label'] == 4] = 1
df2.to_csv('./CICIDS2017_sample_km_infiltration.csv',index=0)

### Read the generated datasets for unknown attack detection

In [64]:
df1 = pd.read_csv('./CICIDS2017_sample_km_without_infiltration.csv')
df2 = pd.read_csv('./CICIDS2017_sample_km_infiltration.csv')

In [65]:
features = df1.drop(['Label'],axis=1).dtypes[df1.dtypes != 'object'].index
df1[features] = df1[features].apply(
    lambda x: (x - x.mean()) / (x.std()))
df2[features] = df2[features].apply(
    lambda x: (x - x.mean()) / (x.std()))
df1.replace([np.inf, -np.inf], np.nan, inplace=True)
df2.replace([np.inf, -np.inf], np.nan, inplace=True)
df1 = df1.fillna(0)
df2 = df2.fillna(0)

In [66]:
df1.Label.value_counts()

Label
1    23805
0    10663
Name: count, dtype: int64

In [67]:
df2.Label.value_counts()

Label
1    1989
Name: count, dtype: int64

In [68]:
df2p=df1[df1['Label']==0]
df2pp=df2p.sample(n=None, frac=1989/10663, replace=False, weights=None, random_state=None, axis=0)
df2=pd.concat([df2, df2pp])

In [69]:
df2.Label.value_counts()

Label
1    1989
0    1989
Name: count, dtype: int64

In [70]:
df = pd.concat([df1, df2])

In [71]:
df

Protocol  Flow Duration  Total Fwd Packets  Total Backward Packets  \
0     -0.394299      -0.552655          -0.223812               -0.073614   
1     -0.394299      -0.552894          -0.223812               -0.073614   
2     -0.394299      -0.553506          -0.223812               -0.073614   
3     -0.394299      -0.552462          -0.223812               -0.073614   
4     -0.394299      -0.554369          -0.223812               -0.073614   
...         ...            ...                ...                     ...   
28496 -0.394299      -0.723334          -0.223585                0.025176   
34357 -0.394299      -0.709764          -0.223509                0.025176   
32289 -0.394299       0.313598          -0.223698               -0.059501   
32266  2.419670      -0.770783          -0.223850               -0.059501   
32514  2.419670      -0.770768          -0.223850               -0.059501   

       Fwd Packets Length Total  Bwd Packets Length Total  \
0                     -0.224843                 -0.030853   
1                     -0.224843                 -0.030853   
2                     -0.224843                 -0.030853   
3                     -0.224843                 -0.030853   
4                     -0.224843                 -0.030853   
...                         ...                       ...   
28496                 -0.223487                 -0.015354   
34357                 -0.223510                 -0.015354   
32289                 -0.224697                 -0.030402   
32266                 -0.224792                 -0.030275   
32514                 -0.224790                 -0.029814   

       Fwd Packet Length Max  Fwd Packet Length Min  Fwd Packet Length Mean  \
0                  -0.709231              -0.233147               -0.834328   
1                  -0.709231              -0.233147               -0.834328   
2                  -0.709231              -0.233147               -0.834328   
3                  -0.709231              -0.233147               -0.834328   
4                  -0.709231              -0.233147               -0.834328   
...                      ...                    ...                     ...   
28496               1.772735              -0.233147                0.988476   
34357               1.714077              -0.233147                0.598511   
32289              -0.540589              -0.233147               -0.521847   
32266              -0.551588               0.930191               -0.288122   
32514              -0.544255               0.984300               -0.262717   

       Fwd Packet Length Std  ...  Fwd Seg Size Min  Active Mean  Active Std  \
0                  -0.679018  ...         -0.374568    -0.373421   -0.296392   
1                  -0.679018  ...         -0.374568    -0.373421   -0.296392   
2                  -0.679018  ...         -0.374568    -0.373421   -0.296392   
3                  -0.679018  ...         -0.374568    -0.373421   -0.296392   
4                  -0.679018  ...         -0.374568    -0.373421   -0.296392   
...                      ...  ...               ...          ...         ...   
28496               1.398741  ...         -0.374568    -0.373421   -0.296392   
34357               1.189346  ...         -0.374568    -0.373421   -0.296392   
32289              -0.467019  ...         -0.374568    -0.341485   -0.296392   
32266              -0.679018  ...         -1.664641    -0.373421   -0.296392   
32514              -0.679018  ...         -1.664641    -0.373421   -0.296392   

       Active Max  Active Min  Idle Mean  Idle Std  Idle Max  Idle Min  Label  
0       -0.372125   -0.359659  -0.150162 -0.405871 -0.264287 -0.066190      1  
1       -0.372125   -0.359659  -0.150162 -0.405871 -0.264287 -0.066190      1  
2       -0.372125   -0.359659  -0.153653 -0.405871 -0.267461 -0.069698      1  
3       -0.372125   -0.359659  -0.150162 -0.405871 -0.264287 -0.066190      1  
4       -0.372125   -0.359659  -0.15365

In [72]:
X = df.drop(['Label'],axis=1) .values
y = df.iloc[:, -1].values.reshape(-1,1)
y=np.ravel(y)
pd.Series(y).value_counts()

1    25794
0    12652
Name: count, dtype: int64

### Feature engineering (IG, FCBF, and KPCA)

#### Feature selection by information gain (IG)

In [73]:
from sklearn.feature_selection import mutual_info_classif
importances = mutual_info_classif(X, y)

In [74]:
# calculate the sum of importance scores
f_list = sorted(zip(map(lambda x: round(x, 4), importances), features), reverse=True)
Sum = 0
fs = []
for i in range(0, len(f_list)):
    Sum = Sum + f_list[i][0]
    fs.append(f_list[i][1])

In [75]:
# select the important features from top to bottom until the accumulated importance reaches 90%
f_list2 = sorted(zip(map(lambda x: round(x, 4), importances/Sum), features), reverse=True)
Sum2 = 0
fs = []
for i in range(0, len(f_list2)):
    Sum2 = Sum2 + f_list2[i][0]
    fs.append(f_list2[i][1])
    if Sum2>=0.9:
        break

In [76]:
X_fs = df[fs].values

In [77]:
X_fs.shape

(38446, 47)

In [78]:
X_fs

array([[-0.22484269, -0.22484269, -0.80677082, ..., -0.06619024,
        -0.15016195, -0.43699582],
       [-0.22484269, -0.22484269, -0.80677082, ..., -0.06619024,
        -0.15016195, -0.43699582],
       [-0.22484269, -0.22484269, -0.80677082, ..., -0.06969809,
        -0.15365256, -0.43699582],
       ...,
       [-0.2246974 , -0.2246974 , -0.70722918, ...,  1.39190593,
         1.30077221, -0.43699582],
       [-0.2247919 , -0.2247919 , -0.67909785, ..., -0.43451416,
        -0.5166767 , -0.43699582],
       [-0.22478953, -0.22478953, -0.57739226, ..., -0.43451416,
        -0.5166767 , -0.43699582]])

#### Feature selection by Fast Correlation Based Filter (FCBF)

The module is imported from the GitHub repo: https://github.com/SantiagoEG/FCBF_module

In [33]:
!pip install scikit-optimizer

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.9/97.9 kB 519.9 kB/s eta 0:00:00


In [79]:
from skopt import gp_minimize
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
import numpy as np

def fcbf_objective(threshold, X, y, clf=RandomForestClassifier(random_state=42)):
    selector = FCBF(th=threshold)
    X_selected = selector.fit_transform(X, y)
    if X_selected.shape[1] == 0:
        return 1.0
    score = cross_val_score(clf, X_selected, y, cv=3, scoring="accuracy").mean()
    return -score

In [80]:
from FCBF_module import FCBF, FCBFK, FCBFiP, get_i
fcbf = FCBF(th = 0.09988304703442026)

In [81]:
X_fss = fcbf.fit_transform(X_fs,y)

In [82]:
X_fss.shape

(38446, 1)

In [83]:
X_fss

array([[-0.65147737],
       [-0.65147737],
       [-0.65147737],
       ...,
       [-0.77199218],
       [-0.78926619],
       [-0.78926619]])

####  kernel principal component analysis (KPCA)

In [ ]:
from skopt import gp_minimize
from skopt.space import Integer, Categorical
from sklearn.decomposition import KernelPCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

def kpca_objective(params, X, y):
    n_components, kernel = params
    n_components = min(n_components, X.shape[1] - 1)
    if n_components < 1: n_components = 1
    try:
        kpca = KernelPCA(n_components=n_components, kernel=kernel, fit_inverse_transform=False, random_state=42)
        X_kpca = kpca.fit_transform(X)
        clf = RandomForestClassifier(random_state=42)
        score = cross_val_score(clf, X_kpca, y, cv=3, scoring="accuracy").mean()
        return -score
    except Exception as e:
        return 1.0

search_space = [
    Integer(10, 50),
    Categorical(['rbf', 'poly'])
]

result = gp_minimize(
    lambda params: kpca_objective(params, X_fss, y),
    search_space,
    n_calls=20,
    random_state=42,
    acq_func='EI'
)

best_n_components, best_kernel = result.x
print(f"Best n_components: {best_n_components}, Best kernel: {best_kernel}")
print(f"Best accuracy: {-result.fun:.4f}")

In [84]:
from skopt import gp_minimize
from skopt.space import Integer, Categorical
from sklearn.decomposition import KernelPCA
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score

kpca = KernelPCA(n_components=20, kernel='rbf', random_state=42)
X_kpca = kpca.fit_transform(X_fss)

In [85]:
X_train = X_kpca[:len(df1)]
y_train = y[:len(df1)]
X_test = X_kpca[len(df1):]
y_test = y[len(df1):]

In [86]:
pd.Series(y_train).value_counts()

1    23805
0    10663
Name: count, dtype: int64

In [87]:
from imblearn.over_sampling import SMOTE
smote=SMOTE(sampling_strategy={0:23805})
X_train, y_train = smote.fit_resample(X_train, y_train)

In [88]:
pd.Series(y_train).value_counts()

1    23805
0    23805
Name: count, dtype: int64

In [89]:
pd.Series(y_test).value_counts()

1    1989
0    1989
Name: count, dtype: int64

### Apply the cluster labeling (CL) k-means method

In [90]:
from sklearn.cluster import KMeans
from sklearn.cluster import DBSCAN,MeanShift
from sklearn.cluster import SpectralClustering,AgglomerativeClustering,AffinityPropagation,Birch,MiniBatchKMeans,MeanShift
from sklearn.mixture import GaussianMixture, BayesianGaussianMixture
from sklearn.metrics import classification_report
from sklearn import metrics

In [91]:
def CL_kmeans(X_train, X_test, y_train, y_test,n,b=100):
    km_cluster = MiniBatchKMeans(n_clusters=n,batch_size=b)
    result = km_cluster.fit_predict(X_train)
    result2 = km_cluster.predict(X_test)

    count=0
    a=np.zeros(n)
    b=np.zeros(n)
    for v in range(0,n):
        for i in range(0,len(y_train)):
            if result[i]==v:
                if y_train[i]==1:
                    a[v]=a[v]+1
                else:
                    b[v]=b[v]+1
    list1=[]
    list2=[]
    for v in range(0,n):
        if a[v]<=b[v]:
            list1.append(v)
        else:
            list2.append(v)
    for v in range(0,len(y_test)):
        if result2[v] in list1:
            result2[v]=0
        elif result2[v] in list2:
            result2[v]=1
        else:
            print("-1")
    print(classification_report(y_test, result2))
    cm=confusion_matrix(y_test,result2)
    acc=metrics.accuracy_score(y_test,result2)
    print(str(acc))
    print(cm)

In [92]:
X_train = X_kpca[:len(df1)]
y_train = y[:len(df1)]
X_test = X_kpca[len(df1):]
y_test = y[len(df1):]
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)
from imblearn.over_sampling import SMOTE
smote=SMOTE(sampling_strategy={0:23805})
X_train, y_train = smote.fit_resample(X_train, y_train)

In [93]:
CL_kmeans(X_train, X_test, y_train, y_test, 8)

              precision    recall  f1-score   support

           0       0.85      0.99      0.91      1989
           1       0.99      0.82      0.90      1989

    accuracy                           0.91      3978
   macro avg       0.92      0.91      0.91      3978
weighted avg       0.92      0.91      0.91      3978

0.905982905982906
[[1966   23]
 [ 351 1638]]


### Hyperparameter optimization of CL-k-means
Tune "k"

In [94]:
#Hyperparameter optimization by BO-GP
from skopt.space import Real, Integer
from skopt.utils import use_named_args
from sklearn import metrics

space  = [Integer(2, 50, name='n_clusters')]
@use_named_args(space)
def objective(**params):
    km_cluster = MiniBatchKMeans(batch_size=100, **params)
    n=params['n_clusters']

    result = km_cluster.fit_predict(X_train)
    result2 = km_cluster.predict(X_val)

    count=0
    a=np.zeros(n)
    b=np.zeros(n)
    for v in range(0,n):
        for i in range(0,len(y_train)):
            if result[i]==v:
                if y_train[i]==1:
                    a[v]=a[v]+1
                else:
                    b[v]=b[v]+1
    list1=[]
    list2=[]
    for v in range(0,n):
        if a[v]<=b[v]:
            list1.append(v)
        else:
            list2.append(v)
    for v in range(0,len(y_val)):
        if result2[v] in list1:
            result2[v]=0
        elif result2[v] in list2:
            result2[v]=1
        else:
            print("-1")
    cm=metrics.accuracy_score(y_val,result2)
    print(str(n)+" "+str(cm))
    return (1-cm)
from skopt import gp_minimize
import time
t1=time.time()
res_gp = gp_minimize(objective, space, n_calls=20, random_state=0)
t2=time.time()
print(t2-t1)
print("Best score=%.4f" % (1-res_gp.fun))
print("""Best parameters: n_clusters=%d""" % (res_gp.x[0]))

30 0.7682042355671599
43 0.7689295039164491
43 0.7677690745575864
43 0.7917029300841312
32 0.7673339135480127
20 0.7434000580214679
16 0.7518131708732231
5 0.5597621119814331
15 0.7232375979112271
25 0.7668987525384392
50 0.7941688424717145
50 0.7695097185958805
37 0.7674789672178706
50 0.7693646649260226
47 0.7677690745575864
50 0.7693646649260226
39 0.7677690745575864
26 0.7657383231795765
46 0.7677690745575864
35 0.7531186539019438
6.985275983810425
Best score=0.7942
Best parameters: n_clusters=50


In [95]:
X_train = X_kpca[:len(df1)]
y_train = y[:len(df1)]
X_test = X_kpca[len(df1):]
y_test = y[len(df1):]
from imblearn.over_sampling import SMOTE
smote=SMOTE(sampling_strategy={0:23805})
X_train, y_train = smote.fit_resample(X_train, y_train)

In [96]:
CL_kmeans(X_train, X_test, y_train, y_test, res_gp.x[0])

              precision    recall  f1-score   support

           0       0.84      0.94      0.89      1989
           1       0.93      0.82      0.88      1989

    accuracy                           0.88      3978
   macro avg       0.89      0.88      0.88      3978
weighted avg       0.89      0.88      0.88      3978

0.8828557063851181
[[1874  115]
 [ 351 1638]]


### Apply the CL-k-means model with biased classifiers

95% of the code has been shared, and the remaining 5% is retained for future extension.  
Thank you for your interest and more details are in the paper.

In [97]:
from sklearn.cluster import MiniBatchKMeans
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import (
    classification_report,
    confusion_matrix,
    accuracy_score,
    recall_score
)
from sklearn.model_selection import StratifiedKFold, train_test_split
from sklearn.neighbors import NearestNeighbors
import numpy as np
from skopt import BayesSearchCV
from skopt.space import Integer
from imblearn.over_sampling import SMOTE

def Anomaly_IDS(X_train, X_test, y_train, y_test, n, b=100):
    km = MiniBatchKMeans(n_clusters=n, batch_size=b, random_state=0)
    train_labels = km.fit_predict(X_train)
    test_labels  = km.predict(X_test)

    counts_pos = np.zeros(n)
    counts_neg = np.zeros(n)
    for idx, c in enumerate(train_labels):
        if y_train[idx] == 1: counts_pos[c] += 1
        else:               counts_neg[c] += 1

    cluster_prob = {}
    normal_clusters = []
    attack_clusters = []
    for c in range(n):
        tot = counts_pos[c] + counts_neg[c]
        if counts_pos[c] > counts_neg[c]:
            attack_clusters.append(c)
            cluster_prob[c] = counts_pos[c] / tot if tot>0 else 0.0
        else:
            normal_clusters.append(c)
            cluster_prob[c] = counts_neg[c] / tot if tot>0 else 0.0

    y_km = np.array([1 if c in attack_clusters else 0 for c in test_labels])

    print("CL-k-means Performance:")
    print(classification_report(y_test, y_km))
    cm = confusion_matrix(y_test, y_km)
    tn, fp, fn, tp = cm.ravel()
    dr = tp/(tp+fn) if tp+fn>0 else 0
    far = fp/(fp+tn) if fp+tn>0 else 0
    print(f"  DR: {dr:.4f}, FAR: {far:.4f}\n  CM:\n{cm}\n")

    y_train_km = np.array([1 if c in attack_clusters else 0 for c in train_labels])
    fp_idx = np.where((y_train_km == 1) & (y_train == 0))[0]
    fn_idx = np.where((y_train_km == 0) & (y_train == 1))[0]

    X_fp = X_train[fp_idx]
    X_fn = X_train[fn_idx]
    X_norm = X_train[y_train == 0]
    X_adv  = X_train[y_train == 1]

    if len(X_fp) and len(X_adv):
        attack_samples_for_fp = X_adv[np.random.choice(len(X_adv), size=len(X_fp),replace=True)]
        Xp = np.concatenate([X_fp, attack_samples_for_fp])
        yp = np.concatenate([np.zeros(len(X_fp)), np.ones(len(X_fp))])
        yp = yp.astype(np.int64)
        y_counts = np.bincount(yp)
        print(y_counts)
        min_groups = np.min(y_counts)
        if min_groups >= 2:
          opt_rfp = BayesSearchCV(
              RandomForestClassifier(random_state=0),
              {
                  'n_estimators': Integer(10,200),
                  'max_depth':    Integer(3,50),
                  'min_samples_split': Integer(2,10)
              },
              n_iter=20,
              cv=StratifiedKFold(5, shuffle=True, random_state=0),
              scoring='f1',
              n_jobs=-1,
              random_state=0
          )
          opt_rfp.fit(Xp, yp)
          rfp = opt_rfp.best_estimator_
        else:
          rfp = RandomForestClassifier(random_state=0).fit(X_train, y_train)
    else:
        rfp = RandomForestClassifier(random_state=0).fit(X_train, y_train)

    if len(X_fn) and len(X_norm):
        normal_samples_for_fn = X_norm[np.random.choice(len(X_norm), size=len(X_fn),replace=True)]
        Xn = np.concatenate([X_fn, normal_samples_for_fn])
        yn = np.concatenate([np.zeros(len(X_fn)), np.ones(len(X_fn))])
        yn = yn.astype(np.int64)
        y_counts = np.bincount(yn)
        print(y_counts)
        min_groups = np.min(y_counts)

        if min_groups >= 2:
          opt_rfn = BayesSearchCV(
              RandomForestClassifier(random_state=0),
              {
                  'n_estimators': Integer(10,200),
                  'max_depth':    Integer(3,50),
                  'min_samples_split': Integer(2,10)
              },
              n_iter=20,
              cv=StratifiedKFold(5, shuffle=True, random_state=0),
              scoring='f1',
              n_jobs=-1,
              random_state=0
          )
          opt_rfn.fit(Xn, yn)
          rfn = opt_rfn.best_estimator_
        else:
          rfn = RandomForestClassifier(random_state=0).fit(X_train, y_train)  # fallback
    else:
        rfn = RandomForestClassifier(random_state=0).fit(X_train, y_train)  # fallback

    probs = np.array([cluster_prob.get(c,0.0) for c in test_labels])
    best_thr, best_rec = 0.5, 0.0
    for thr in np.linspace(0.5, 0.99, 50):
        y_tmp = y_km.copy()
        for i, p in enumerate(probs):
            if p < thr:
                if y_tmp[i] == 0:
                    y_tmp[i] = rfn.predict(X_test[i].reshape(1,-1))[0]
                else:
                    y_tmp[i] = rfp.predict(X_test[i].reshape(1,-1))[0]
        rec = recall_score(y_test, y_tmp)
        if rec > best_rec:
            best_rec, best_thr = rec, thr

    y_final = y_km.copy()
    for i, p in enumerate(probs):
        if p < best_thr:
            if y_final[i] == 0:
                y_final[i] = rfn.predict(X_test[i].reshape(1,-1))[0]
            else:
                y_final[i] = rfp.predict(X_test[i].reshape(1,-1))[0]


    print("MTH-IDS Performance:")
    print(classification_report(y_test, y_final))
    cm2 = confusion_matrix(y_test, y_final)

    tn, fp, fn, tp = cm2.ravel()
    dr2 = tp/(tp+fn) if tp+fn>0 else 0
    far2 = fp/(fp+tn) if fp+tn>0 else 0
    acc2 = accuracy_score(y_test, y_final)

    print(f"  Acc: {acc2:.4f}, DR: {dr2:.4f}, FAR: {far2:.4f}\n  CM:\n{cm2}")

    return acc2, dr2, far2, cm2

In [98]:
X_train = X_kpca[:len(df1)]
y_train = y[:len(df1)]
X_test = X_kpca[len(df1):]
y_test = y[len(df1):]
X_train, X_val, y_train, y_val = train_test_split(X_train, y_train, test_size=0.2, random_state=42)
from imblearn.over_sampling import SMOTE
smote=SMOTE(sampling_strategy={1:21313})
X_train, y_train = smote.fit_resample(X_train, y_train)

In [99]:
one_acc, one_dr, one_far, one_f1 = Anomaly_IDS(X_train, X_test, y_train, y_test, res_gp.x[0])

CL-k-means Performance:
              precision    recall  f1-score   support

           0       0.79      0.66      0.72      1989
           1       0.71      0.82      0.76      1989

    accuracy                           0.74      3978
   macro avg       0.75      0.74      0.74      3978
weighted avg       0.75      0.74      0.74      3978

  DR: 0.8235, FAR: 0.3363
  CM:
[[1320  669]
 [ 351 1638]]

[3672 3672]
[1610 1610]
MTH-IDS Performance:
              precision    recall  f1-score   support

           0       0.79      0.66      0.72      1989
           1       0.71      0.82      0.76      1989

    accuracy                           0.74      3978
   macro avg       0.75      0.74      0.74      3978
weighted avg       0.75      0.74      0.74      3978

  Acc: 0.7436, DR: 0.8235, FAR: 0.3363
  CM:
[[1320  669]
 [ 351 1638]]
